### PR TITLE
Improve focus styles and general accessibility of some components

### PR DESCRIPTION
**Pull request by axelboc**
Improve focus styles of various components and parts of the injection (based off the work of @anormand: #550), deprecate disabled state of pathfinder boxes, and improve markup and documentation of disabled buttons.

Also, fix positioning of jumpnav on refresh and tweak design of footer and global sitemap:

- reduce space around quicklinks to make it clear that there is a second row of sitemap blocks
- reduce space around indigenous statement and restore quicklinks bottom border above it
- improve hover and focus styles
- fix vertical alignment of social icons
- use multiples of 16px and its divisors (8px, 4px) for margin and padding where possible (e.g. `32px` instead of `30px`) in order for the computed `rem` values to be rounder

### Breaking changes!
The `disabled` state/class for [pathfinder](http://web.unimelb.edu.au/components/pathfinder/) boxes is now deprecated. A note has been added to suggest a couple of alternatives.

[Disabled buttons](http://web.unimelb.edu.au/components/buttons#disabled-buttons) are now documented and their markup has been formalised. A distinction is now made between a button implemented with an `<a>`nchor element vs. with a `<button>` or `<input>` element. The former requires the `disabled` class along with the `aria-disabled="true"` and `tabindex="-1"` attributes, while the latter simply requires the `disabled` attribute.

```html
<!-- BEFORE -->
<a class="button disabled" href="#">Foo</a>
<button class="button disabled">Foo</button>

<!-- AFTER -->
<a class="button disabled" href="#" aria-disabled="true" tabindex="-1">Foo</a>
<button class="button" disabled>Foo</button>
```

### CODE REVIEW

**Comment by axelboc** [comment]
Okay, this should be ready to go. Heaps of small tweaks in this one...

**Comment by waitingallday** [comment]
Huge! Will start testing this tomorrow

**Comment by anormand** [comment]
Great work Axel! 
This is one of those great changes that makes things easier for everyone (even they probably won't realize it).

**Comment by axelboc** [comment]
This PR had become quite stale. I've pulled the changes from master and fixed conflicts.

Unfortunately, I just remembered that the `disabled` attribute is not valid on anchor elements... Silly me. 😞 It's still important to have `tabindex="-1"`, but I'll revert the rest of the changes I made to the buttons and pathfinder components. The `disabled` class is the best way to go. Actually, to be fully accessible without the `disabled` attribute, we need the `aria-disabled` attribute along with `tabindex="-1"`!

Not sure if adding these two attributes still constitutes a breaking change. In my opinion it does, as from a user's perspective, we change the way a component is meant to be disabled.

Now, as it turns out, disabled links in the design system are still clickable! (The `disabled` attribute didn't even fix that...) This can be seen on the doc page of the pathfinder component. So while I'm at it, I'll fix this using `pointer-events: none` to prevent clicks from having any effect and to disable hover effects altogether (instead of overriding all the hover styles). This property is not supported in IE10 and below, but since the behaviour was already broken, it won't make a difference; at least it will fix modern browsers.

**Comment by axelboc** [comment]
As discussed, I've deprecated the disabled state for pathfinder boxes, and reverted back to the `disabled` class (as opposed to the `disabled` attribute) for disabled buttons. I've updated the PR's description with more details.

**Pull request merged**
