### PR TITLE
Escape numeric id for smooth scroll

### PR DESCRIPTION
**Pull request by waitingallday**
Queryselector can only match an ID that starts with a number *if the string is escaped*.

eg. using `<h2 id="2012">Photos from 2012</h2>` as an anchor to the jump nav will cause a DOM Exception 12, originating from the queryselector call.

This PR introduces an external dependency, `cssesc`, to escape the ID string.

Ref: https://mathiasbynens.be/notes/css-escapes

### CODE REVIEW

**Comment by axelboc** [comment]
There are a few other places where we query elements with the URL hash. Do you reckon we should make those safe as well?

**Comment by waitingallday** [comment]
Absolutely! I was trying to think of where else it would be used, but came up blank.

**Comment by axelboc** [comment]
Hmm I think the tabs, sidebar tabs, and filtered listing. That's what came up when I searched for `location.`. I'll take a look at it once #607 is merged if you want.

**Comment by waitingallday** [comment]
Will look at this monday, and merge!

**Comment by waitingallday** [comment]
Have renamed `movetab` to `movetabpanel` - I was getting a little confused between the movement of _tabs_ and the _tabpanels_, especially since smoothscroll on the tab overflow was added 😄

**Comment by axelboc** [comment]
Ah yeah nice, it was bugging me too.

**Pull request merged**
