### PR TITLE
Upgrade to node 4.2.1 and related dependencies

### PR DESCRIPTION
**Pull request by waitingallday**
Current stable version!

### CODE REVIEW

**Comment by axelboc** [comment]
I get an error when running `rake assets:build`:

```
An error occured in task 'manifest:digest'.
/Users/axelboc/unimelb-design-system/node_modules/gulp/node_modules/orchestrator/index.js:153
			throw err;
			^

TypeError: Cannot read property 'on' of undefined
    at DestroyableTransform.Readable.pipe (/Users/axelboc/unimelb-design-system/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:516:7)
    at Gulp.<anonymous> (/Users/axelboc/unimelb-design-system/assets/precompile.js:19:6)
...
```

**Comment by waitingallday** [comment]
It mentioned something about explicitly including dependencies, there might be a few that are now needed - will look into it

**Comment by waitingallday** [comment]
I fixed that bug just now on a different branch - the version of `sass-loader` we were using was referencing a much older `node-sass`.

`npm outdated` FTW

**Comment by axelboc** [comment]
Awesome! I've always used a package called `npm-check-updates` in the past - I'll give `npm outdated` a go!

**Pull request merged**
