### PR TITLE
Tables - Better headers added complex tables

### PR DESCRIPTION
**Pull request by anormand**

### CODE REVIEW

**Comment by waitingallday** [comment]
We need to be really careful with using IDs (I don't use them at all for styling any more, and try to avoid them in javascript as well), since the names need to be unique. Ideally, I would want to leave the entire ID namespace open for use by the site developers using this sytem

Maybe we need a universal naming scheme? eg. for accessibility-related IDs, maybe have an aria- prefix?

**Comment by anormand** [comment]
That's a good idea but 'aria-' might not be so good because there are attributes with this prefix as part of WAI-ARIA technique. Perhaps 'acc-[id name]' or 'wcag-[id name]'?

**Comment by waitingallday** [comment]
Sounds good, I think i prefer wcag- to acc-, makes it really unambiguous as to why it's there.

**Comment by anormand** [comment]
wcag prefix now added

**Pull request merged**
